module.exports = {
  ANIMATION: 'ANIMATION',
  INIT_TIME_SYNC: 'INIT_TIME_SYNC',
  POSITION: 'POSITION',
  SERVER_TIME: 'SERVER_TIME',
  SET_SEQUENCE: 'SET_SEQUENCE',
  START_ANIMATION: 'START_ANIMATION',
  STOP_ANIMATION: 'STOP_ANIMATION',
  NEW_CONNECTIONS: 'connections/NEW_CONNECTIONS',
  CLOSED_CONNECTIONS: 'connections/CLOSED_CONNECTIONS',
  CURRENT_CONNECTIONS: 'connections/CURRENT_CONNECTIONS',
  ALL_SEQUENCES: 'sequences/ALL_SEQUENCES',
  DIMENSIONS: 'dimensions/DIMENSIONS',
};
